"""
CV Scoring Service
==================
Contains the pure business logic for scoring a candidate against a job description.
This service is strictly decoupled from LangChain/AI orchestration frameworks.

Responsibilities:
  1. Fetch candidate + JD data from the DB (via application_id)
  2. Prepare prompts for the LLM
  3. Store the scoring result back to the DB
  4. Verify the LLM's weighted score matches its own category breakdown
"""
from __future__ import annotations

import logging
from datetime import datetime, UTC
from typing import Dict, Any, Tuple
from uuid import UUID

from app.ai.schema.agent_cv_scoring import AgentCVScoreOutput
from app.core.llm_prompt_keys import LLM_USE_CASE_CV_SCORER
from app.services.ai.llm_prompt_repository import load_active_prompt_map, resolve_full_prompt
from app.ai.prompts.cv_scorer import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
from app.db.session import SessionLocal
from app.db.models.candidate_details import Candidate
from app.db.models.job_description import JobDescription
from app.db.models.candidate_application import CandidateApplication
from app.db.models.cv_score import CVScore

logger = logging.getLogger(__name__)

FALLBACK_SYSTEM_PROMPT = SYSTEM_PROMPT


# ---------------------------------------------------------------------------
# 1. FETCH — Get candidate + JD data from the DB
# ---------------------------------------------------------------------------

def fetch_scoring_inputs(application_id: str) -> Dict[str, Any]:
    """
    Given an application_id, fetch the Candidate profile and JobDescription
    (including its structured rubric) from the database.

    Returns a dict with keys: application, candidate, job, structured_output
    """
    try:
        parsed_uuid = UUID(application_id)
    except ValueError:
        raise ValueError(f"Invalid application UUID format: {application_id}")

    db = SessionLocal()
    try:
        # Get the application (the link between candidate and job)
        application = db.query(CandidateApplication).filter(
            CandidateApplication.id == parsed_uuid
        ).first()
        if not application:
            raise ValueError(f"No application found with ID {application_id}")

        # Get the candidate
        candidate = db.query(Candidate).filter(
            Candidate.id == application.candidate_id
        ).first()
        if not candidate:
            raise ValueError(f"No candidate found with ID {application.candidate_id}")

        # Get the job description (contains structured_output with the rubric)
        job = db.query(JobDescription).filter(
            JobDescription.id == application.job_id
        ).first()
        if not job:
            raise ValueError(f"No job description found with ID {application.job_id}")

        if not job.structured_output:
            raise ValueError(
                f"Job description {job.id} has no structured_output (rubric). "
                "Was this JD generated by the agent?"
            )

        # Package candidate data as a clean dict for the prompt
        candidate_data = {
            "full_name": candidate.full_name,
            "email": candidate.email,
            "skills": candidate.skills or {},
            "total_experience": candidate.total_experience,
            "work_experience": candidate.work_experience or [],
            "projects": candidate.projects or [],
            "education": candidate.education or [],
            "certifications": candidate.certifications or [],
            "highlights": candidate.highlights or [],
            "primary_domain": candidate.primary_domain,
            "seniority_level": candidate.seniority_level,
            "cv_text": candidate.cv_text,
        }

        return {
            "application_id": str(application.id),
            "candidate_id": str(candidate.id),
            "job_id": str(job.id),
            "candidate_data": candidate_data,
            "jd_text": job.jd_text,
            "structured_output": job.structured_output,  # Contains the rubric + weighting
        }
    finally:
        db.close()


# ---------------------------------------------------------------------------
# 2. PROMPT — Prepare prompts for the LLM
# ---------------------------------------------------------------------------

def prepare_cv_scorer_prompts(scoring_inputs: Dict[str, Any]) -> Tuple[str, str]:
    """
    Business logic to prepare the prompts for the CV Scoring LLM.
    Resolves the system prompt from the DB (or uses fallback) and formats
    the user prompt with candidate data + JD rubric.

    Returns:
        tuple[str, str]: (system_prompt, user_prompt)
    """
    db = SessionLocal()
    try:
        active_prompts = load_active_prompt_map(db, LLM_USE_CASE_CV_SCORER)
        system_prompt = resolve_full_prompt(active_prompts, "system", FALLBACK_SYSTEM_PROMPT)
    finally:
        db.close()

    structured = scoring_inputs["structured_output"]
    weighting = structured.get("weighting", {
        "skills": 0.45, "experience": 0.25, "projects": 0.20, "education": 0.10
    })

    import json
    user_prompt = USER_PROMPT_TEMPLATE.format(
        jd_text=scoring_inputs["jd_text"],
        must_have_skills=json.dumps(structured.get("must_have_skills", []), indent=2),
        nice_to_have_skills=json.dumps(structured.get("nice_to_have_skills", []), indent=2),
        responsibilities=json.dumps(structured.get("responsibilities", []), indent=2),
        tools_and_technologies=json.dumps(structured.get("tools_and_technologies", []), indent=2),
        education_requirements=json.dumps(structured.get("education", []), indent=2),
        experience_required=structured.get("experience_required", "Not specified"),
        weighting=json.dumps(weighting, indent=2),
        candidate_name=scoring_inputs["candidate_data"].get("full_name", "Unknown"),
        candidate_skills=json.dumps(scoring_inputs["candidate_data"].get("skills", {}), indent=2),
        candidate_experience=scoring_inputs["candidate_data"].get("total_experience", "Unknown"),
        candidate_work_history=json.dumps(scoring_inputs["candidate_data"].get("work_experience", []), indent=2),
        candidate_projects=json.dumps(scoring_inputs["candidate_data"].get("projects", []), indent=2),
        candidate_education=json.dumps(scoring_inputs["candidate_data"].get("education", []), indent=2),
        candidate_certifications=json.dumps(scoring_inputs["candidate_data"].get("certifications", []), indent=2),
        candidate_highlights=json.dumps(scoring_inputs["candidate_data"].get("highlights", []), indent=2),
        cv_text=scoring_inputs["candidate_data"].get("cv_text", ""),
    )

    return system_prompt, user_prompt


# ---------------------------------------------------------------------------
# 3. VERIFY — Recalculate the weighted score from category scores
# ---------------------------------------------------------------------------

def verify_weighted_score(
    agent_output: AgentCVScoreOutput,
    weighting: Dict[str, float],
    tolerance: float = 2.0
) -> float:
    """
    Recalculate raw_score from category_scores × weighting.
    If the LLM's raw_score differs by more than `tolerance`, use the
    recalculated value instead.

    Returns the verified (possibly corrected) raw_score.
    """
    calculated = (
        agent_output.category_scores.skills * weighting.get("skills", 0.45)
        + agent_output.category_scores.experience * weighting.get("experience", 0.25)
        + agent_output.category_scores.projects * weighting.get("projects", 0.20)
        + agent_output.category_scores.education * weighting.get("education", 0.10)
    )
    calculated = round(calculated, 2)

    if abs(agent_output.raw_score - calculated) > tolerance:
        logger.warning(
            f"LLM raw_score ({agent_output.raw_score}) differs from calculated "
            f"({calculated}) by more than {tolerance} points. Using calculated value."
        )
        return calculated

    return agent_output.raw_score


# ---------------------------------------------------------------------------
# 4. STORE — Persist the score result to the DB
# ---------------------------------------------------------------------------

def store_cv_score(
    candidate_id: str,
    job_id: str,
    application_id: str,
    agent_output: AgentCVScoreOutput,
    verified_score: float,
    scoring_model: str = "unknown",
) -> Dict[str, Any]:
    """
    Take the LLM's AgentCVScoreOutput and persist it into the `cv_score` table.
    Also updates the candidate_application status to 'scored'.

    Handles re-scoring: if a score already exists for this (candidate, job) pair,
    increments the version instead of creating a duplicate.

    Returns a summary dict with score_id, raw_score, status.
    """
    try:
        parsed_candidate_id = UUID(candidate_id)
        parsed_job_id = UUID(job_id)
        parsed_application_id = UUID(application_id)
    except ValueError as e:
        raise ValueError(f"Invalid UUID format: {e}")

    db = SessionLocal()
    try:
        # --- Duplicate / re-score check ---
        existing = db.query(CVScore).filter(
            CVScore.candidate_id == parsed_candidate_id,
            CVScore.job_id == parsed_job_id,
        ).order_by(CVScore.version.desc()).first()

        new_version = (existing.version + 1) if existing else 1

        # --- Create the CVScore record ---
        cv_score = CVScore(
            job_id=parsed_job_id,
            candidate_id=parsed_candidate_id,
            raw_score=verified_score,
            confidence=agent_output.confidence,
            strengths=agent_output.strengths,
            weaknesses=agent_output.weaknesses,
            evidence=[e.model_dump() for e in agent_output.evidence],
            reasoning_summary=agent_output.reasoning_summary,
            category_scores=agent_output.category_scores.model_dump(),
            status="scored",
            version=new_version,
            scored_by="cv_scoring_agent",
            scoring_model=scoring_model,
            scored_at=datetime.now(UTC),
        )

        db.add(cv_score)

        # --- Update application status ---
        application = db.query(CandidateApplication).filter(
            CandidateApplication.id == parsed_application_id
        ).first()
        if application:
            application.status = "scored"

        db.commit()
        db.refresh(cv_score)

        return {
            "score_id": str(cv_score.id),
            "candidate_id": candidate_id,
            "job_id": job_id,
            "raw_score": cv_score.raw_score,
            "confidence": cv_score.confidence,
            "version": cv_score.version,
            "status": "scored",
        }

    except Exception as e:
        db.rollback()
        logger.error(f"Failed to store CV score: {e}")
        raise
    finally:
        db.close()
