"""add jd_intake table

Revision ID: 2147d5ccb976
Revises: 4e0ebb03221a
Create Date: 2026-04-21 01:06:06.537876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2147d5ccb976'
down_revision: Union[str, None] = '4e0ebb03221a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_intake',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Name of the hiring company'),
    sa.Column('salary_min', sa.Float(), nullable=True, comment='Lower bound of salary range (in local currency)'),
    sa.Column('salary_max', sa.Float(), nullable=True, comment='Upper bound of salary range (in local currency)'),
    sa.Column('experience_min', sa.Float(), nullable=True, comment='Minimum years of professional experience required'),
    sa.Column('experience_max', sa.Float(), nullable=True, comment='Maximum years of experience (cap for the band)'),
    sa.Column('domain', sa.String(length=100), nullable=True, comment='Industry/domain: engineering, marketing, data, design, finance, etc.'),
    sa.Column('role_type', sa.String(length=50), nullable=True, comment='One of: intern, full-time, part-time, contract, freelance'),
    sa.Column('preferred_education', sa.String(length=50), nullable=True, comment='One of: any, diploma, bachelors, masters, phd'),
    sa.Column('location', sa.String(length=255), nullable=True, comment="Office location or 'Remote'"),
    sa.Column('description', sa.Text(), nullable=False, comment='Free-text description written by the recruiter summarizing the role'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jd_intake')
    # ### end Alembic commands ###
