"""add dynamic llm prompts table

Revision ID: 4e0ebb03221a
Revises: 67b4814dfba3
Create Date: 2026-04-19 19:42:22.976858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0ebb03221a'
down_revision: Union[str, None] = '67b4814dfba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_llm_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('use_case', sa.String(length=50), nullable=False),
    sa.Column('variant_key', sa.String(length=50), nullable=False),
    sa.Column('prompt_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('use_case', 'variant_key', name='uq_dynamic_prompts_usecase_variant')
    )
    op.create_index(op.f('ix_dynamic_llm_prompts_use_case'), 'dynamic_llm_prompts', ['use_case'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dynamic_llm_prompts_use_case'), table_name='dynamic_llm_prompts')
    op.drop_table('dynamic_llm_prompts')
    # ### end Alembic commands ###
