"""add_candidate_application_table

Revision ID: 5553bbc865da
Revises: d0c36eff53cb
Create Date: 2026-04-30 01:45:21.199646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5553bbc865da'
down_revision: Union[str, None] = 'd0c36eff53cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_details.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_description.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job')
    )
    op.create_index(op.f('ix_candidate_application_candidate_id'), 'candidate_application', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_application_job_id'), 'candidate_application', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_application_job_id'), table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_candidate_id'), table_name='candidate_application')
    op.drop_table('candidate_application')
    # ### end Alembic commands ###
