"""add_bias_report_table

Revision ID: 67b4814dfba3
Revises: 53a222838357
Create Date: 2026-04-19 15:47:49.871350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67b4814dfba3'
down_revision: Union[str, None] = '53a222838357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_score_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level_enum'), nullable=False),
    sa.Column('bias_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bias_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitigation_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('reviewed_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('detected_by', sa.String(length=100), nullable=True),
    sa.Column('detection_model', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_details.id'], ),
    sa.ForeignKeyConstraint(['cv_score_id'], ['cv_score.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_description.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bias_report')
    # ### end Alembic commands ###
