"""Add jd_intake_id FK to job_description

Revision ID: d0c36eff53cb
Revises: 2147d5ccb976
Create Date: 2026-04-24 22:02:18.537717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c36eff53cb'
down_revision: Union[str, None] = '2147d5ccb976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_description', sa.Column('jd_intake_id', sa.UUID(), nullable=True, comment='FK to jd_intake — the recruiter form that triggered this JD generation'))
    op.create_foreign_key(None, 'job_description', 'jd_intake', ['jd_intake_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_description', type_='foreignkey')
    op.drop_column('job_description', 'jd_intake_id')
    # ### end Alembic commands ###
